INPUT "ENTER YOUR NAME: ", Y$
LET SCORE = 0
LET TOTAL = 0
RAM:
RANDOMIZE TIMER / 3

CLS
PRINT "SCORE/TOTAL:"; SCORE; "/"; TOTAL
LET A = INT(RND * 20)
LET B = INT(RND * 10)
PRINT A; "*"; B; "=?";
INPUT C
IF A * B = C THEN
    PRINT "CORRECT"
    A$ = "CORRECT"
    LET SCORE = SCORE + 1
    LET TOTAL = TOTAL + 1
ELSE
    PRINT "INCORRECT"
    A$ = "INCORRECT"
    LET TOTAL = TOTAL + 1
END IF
CLS
PRINT "SCORE/TOTAL:"; SCORE; "/"; TOTAL
PRINT "ANSWER IS: "; A$
INPUT "PRESS P KEY TO PLAY AGAIN, Y TO EXIT", Y$
IF Y$ = "Y" THEN
    END
ELSE
    GOTO RAM
END IF

